### ISSUE TITLE
Should methods decorated with `classmethod` be converted to endpoints automatically?

### ISSUE THREAD

**Issue by maxcountryman** [apiguy/flask-classy#15]
Currently it seems that decorating a method on a `FlaskView` object with a @classmethod does not exclude it from being generated as an endpoint. However it seems like the desirable approach would be to not implicitly include classmethods as views.

**Comment by apiguy** [comment]
I agree with this - I should be able to sort out which methods are class views and exclude them in the `find_member_methods` method.

**Comment by maxcountryman** [comment]
@joeshaw originally raised this issue, pinging him so he can follow the discussion as well.

**Comment by joeshaw** [comment]
Personally, I'd love the ability to disable automatically creating endpoints altogether.

Our code needs to use the `@route` decorator directly because we have our own `Blueprint` subclass that handles authentication, and we need to pass that into the `Rule`.  Automatically creating an endpoint opens up the possibility for accidentally (and without any authentication!) exposing functions externally.  It feels dangerous to me.

**Comment by joeshaw** [comment]
Which is not to say that I think the feature should be removed entirely -- it can be a nice convenience -- just that it'd be nice if there were a class variable like `route_base` I could set to turn that off.

**Comment by apiguy** [comment]
@joeshaw - you aren't the first to request that feature actually. What I've struggled with is where to scope that. Would it be a parameter passed to the register method or maybe an attribute of the FlaskView that could be set (or maybe both might be useful). I think this likely deserves it's own separate issue.
