### ISSUE TITLE
Another inheritance issue

### ISSUE THREAD

**Issue by ivan-kleshnin** [apiguy/flask-classy#39]
I do not quite understand why you choose to change werkzeug approach to endpoint namings. 
Be it right or wrong, we have a problem now :)

> We want to make index page access _done right_ without famous SEO duplicate-content issue.
> E.g. `posts/page/1` should always redirect to `posts/page/`.

**Try 1.**

``` python
from flask.ext.classy import FlaskView, route

class GenericView(FlaskView):
    @route('/page/<int(1):page>')   
    @route('/', defaults={'page': 1}) 
    def index(self, page):
        pass

class PostsView(GenericView):
    ...
```

Now we have ugly endpoints `index_1` and `index_0`. Worst of all, now we forced to check page number before using `url_for`. We do have options `url_for('...index_1')` or `url_for('...index_0')` every time! This is awkward.
Docs say we can customize endpoints...

**Try 2.**

``` python
class GenericView(FlaskView):
    @route('/page/<int(1):page>', endpoint='GenericView:index')
    @route('/', defaults={'page': 1}, endpoint='GenericView:index')
    def index(self, page):
        pass

class PostsView(GenericView):
    ...
```

Oops... Now we are bound to class name! `app.url_map` will contain `GenericView:index`,
instead of desired `PostsView:index` routes.

**Solution**

I see several. For example we can add placeholder support for endpoints.

``` python
@flask.ext.classy.route('/page/<int(1):page>', endpoint='{cls}:index')
@flask.ext.classy.route('/', defaults={'page': 1}, endpoint='{cls}:index')
    def index(self, page):
```

To support this, we should add 1 line of code:

``` python
# /flask-classy.py
class FlaskView(_FlaskViewBase):
    ...
    @classmethod
    def register(cls, app, route_base=None, subdomain=None):
        ...
        # Endpoint placeholder support               # add this
        endpoint = endpoint.format(cls=cls.__name__) # 

        app.add_url_rule(rule, endpoint, proxy, subdomain=subdomain, **options) # before this line (unique)
        ...
```

**Comment by apiguy** [comment]
So there are 2 parts to this, I think.

The first part is the convention of "<ClassName>:<MethodName>" for the default endpoint. The reason for this convention was basically because I needed a way to disambiguate between `ThisView.index` and `ThatView.index`. By default, Flask will only use the method name when deciding on an endpoint and that is not specific enough. I support the idea of using a "{cls}:<endpoint>" to help support inheritance though.

The second part is the "_0" convention for disambiguating between specific routes on a single view. First of all I agree, this sucks. I remember why I did it, but in hindsight it's pretty edge case specific and I doubt anyone is doing what I was doing back then - including myself. I think it would be worth making a change to this behavior and just going with the Werkzeugy style for this behavior. Since that would be a breaking change for existing applications I'm thinking that releasing a change like that would increment the major version number to 0.7.

**Comment by ivan-kleshnin** [comment]
Aha, its getting clearer. Thanks for the response.
